name: Daily PC Part Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the job every day at midnight UTC
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run scraper
      run: npm run start
      
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update PC part data" && git push)