name: Update PC Parts Data

on:
  schedule:
    - cron: '0 1 * * *'  # This runs the job every day at 1 AM UTC
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Download latest data
      run: |
        mkdir -p data
        curl -L https://github.com/rhattala/pc-part-dataset/archive/main.zip -o pc-part-dataset.zip
        unzip pc-part-dataset.zip
        cp pc-part-dataset-main/data-staging/json/* data/
        rm -rf pc-part-dataset-main pc-part-dataset.zip
      
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update PC part data" && git push)
        
    - name: Trigger Netlify rebuild
      if: success()
      run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}